version: '3.8'

services:
  web:
    build:
      context: .
    restart: unless-stopped
    command: gunicorn creatives_discord_bot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/app/static
      - ./images:/app/images
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  bot:
    build:
      context: .
    restart: unless-stopped
    command: ./manage.py run_bot
    volumes:
      - ./static:/app/static
      - ./images:/app/images
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
