version: '3.8'

services:
  web:
    build:
      context: .
    restart: unless-stopped
    command: gunicorn creatives_discord_bot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - images_volume:/app/images
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  bot:
    build:
      context: .
    restart: unless-stopped
    command: ./manage.py run_bot
    volumes:
      - static_volume:/app/staticfiles
      - images_volume:/app/images
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
  static_volume:
  images_volume: