# Generated by Django 4.1.2 on 2022-12-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('start', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('discord_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=256)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('registered', models.DateField(auto_now=True)),
                ('lives', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('file_url', models.URLField()),
                ('media_type', models.CharField(max_length=128)),
                ('submitted_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.user')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspirationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
            options={
                'unique_together': {('user', 'submission')},
            },
        ),
    ]
